In [1]:
 import numpy as np

In [2]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
arr=np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
print("An array of integers from 10 to 50")
arr= np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [7]:
print("An array of all the even integers from 10 to 50")
arr=np.arange(10,51,2)
print(arr)

An array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [12]:
print("3x3 matrix with values ranging from 0 to 8")
np.arange(0,9).reshape(3,3)

3x3 matrix with values ranging from 0 to 8


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
print("3x3 identity matrix")
np.eye(3)

3x3 identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
print("array of 20 linearly spaced points between 0 and 1:")
np.linspace(0,1,20)

array of 20 linearly spaced points between 0 and 1:


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
print("Numpy Indexing and Selection")
matrix = np.arange(1,26).reshape(5,5)
print(matrix)

Numpy Indexing and Selection
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [25]:
matrix[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
matrix[3,4]

20

In [16]:
matrix[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [17]:
 matrix[4:,0:5]

array([[21, 22, 23, 24, 25]])

In [21]:
matrix[3:,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
print ("sum of all the values in matrix")
matrix.sum()

sum of all the values in matrix


325

In [23]:
print("standard deviation of the values in mat")
matrix.std()

standard deviation of the values in mat


7.211102550927978

In [24]:
print("sum of all colums in matrix")
matrix.sum(axis=0)

sum of all colums in matrix


array([55, 60, 65, 70, 75])